name: Lighthouse CI

on:
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Lighthouse CI
        run: npx lighthouse-ci https://www.nashtechglobal.com/ --upload.target=temporary-public-storage
        env:
          LH_API_KEY: ${{ secrets.LH_API_KEY }}
